language: objective-c
os:
    - osx
osx_image: xcode9
podfile: Demo/Podfile

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace Demo/Demo.xcworkspace -scheme Demo -sdk iphonesimulator  -configuration Debug | xcpretty -c
